--* DISPLAY REGION WISE COUNTRIES
SELECT R.region_name, C.COUNTRY_NAME
FROM REGIONS R JOIN COUNTRIES C
ON C.REGION_ID = R.region_id
GROUP BY R.region_name, C.COUNTRY_NAME;

--* DISPLAY COUNTRY WISE LOCATIONS
SELECT C.COUNTRY_NAME, L.CITY, L.STATE_PROVINCE
FROM COUNTRIES C JOIN LOCATIONS L
ON C.COUNTRY_ID = L.COUNTRY_ID
GROUP BY C.COUNTRY_NAME, L.CITY, L.STATE_PROVINCE;

--* REGION DOES NOT HAVE ANY COUNTRY
SELECT R.region_name
FROM REGIONS R
LEFT OUTER JOIN COUNTRIES C
ON C.REGION_ID = R.region_id
WHERE C.COUNTRY_NAME IS NULL;

--* COUNTRY DOES NOT HAVE ANY LOCATIONS
SELECT C.COUNTRY_NAME
FROM COUNTRIES C
LEFT OUTER JOIN LOCATIONS L
ON C.COUNTRY_ID = L.COUNTRY_ID
WHERE L.LOCATION_ID IS NULL;

--* DIPALY COUNTRY NAME AND THIER REGION NAME
SELECT C.COUNTRY_NAME, R.region_name
FROM REGIONS R
JOIN COUNTRIES C
ON C.REGION_ID = R.region_id;

--* DISPALY THE COUNTRY NAME, REGION, LOCATION
SELECT C.COUNTRY_NAME, R.region_name, L.CITY
FROM REGIONS R
JOIN COUNTRIES C
ON C.REGION_ID = R.region_id
JOIN LOCATIONS L
ON C.COUNTRY_ID = L.COUNTRY_ID;

--* DISPALY FULL ADDRESS OF SWABHAV TECH
SELECT L.STREET_ADDRESS,L.POSTAL_CODE, L.CITY, L.STATE_PROVINCE, C.COUNTRY_NAME, R.region_name
FROM REGIONS R
JOIN COUNTRIES C
ON C.REGION_ID = R.region_id
JOIN LOCATIONS L
ON C.COUNTRY_ID = L.COUNTRY_ID
WHERE LOCATION_ID = 2000;