delimiter //
CREATE PROCEDURE DO_TRANSACTION (IN C_ACC INT, IN M_ACC INT, IN AMOUNT FLOAT)
BEGIN

	START TRANSACTION;
	
	UPDATE customer SET BALANCE = BALANCE - AMOUNT WHERE ACCOUNT_NO = C_ACC;
	UPDATE merchant SET BALANCE = BALANCE + AMOUNT WHERE ACCOUNT_NO = M_ACC;
	
	COMMIT;
	
	ROLLBACK;

END//


CALL DO_TRANSACTION (101, 1001, 5000);
UPDATE customer SET BALANCE = BALANCE + 5000 WHERE ACCOUNT_NO = 101;
