INSERT INTO bank_master 
VALUES ("DHEERAJ", "DHEERAJ123", 1000);

INSERT INTO bank_master 
VALUES ("VIPUL", "VIPUL123", 1000);

UPDATE bank_master 
SET BALANCE = 500, PASSWORD = "DHEERAJ123"
WHERE NAME = "DHEERAJ";

UPDATE bank_master 
SET BALANCE = 500, PASSWORD = "PRASAD123"
WHERE NAME = "PRASAD";
