--* display all emp in ascending order
SELECT *
FROM EMP
ORDER BY ENAME;
--* display all emp in dept 10
SELECT *
FROM EMP
WHERE DEPTNO = 10;
--* display all emp whose commission is null
SELECT *
FROM EMP
WHERE COMM IS NULL;
--* display emp name in starting with 's'
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'S%';
--* display emp who are managers
SELECT *
FROM EMP
WHERE EMPNO IN 
			(SELECT MGR
			 FROM EMP
			);
--* display top 2 salary examine emp
SELECT TOP 2 SAL, ENAME
FROM EMP
ORDER BY SAL DESC;
--* display emp name in small case
SELECT LOWER(ENAME) AS ENAME
FROM EMP
--* display emp details with ctc column
SELECT *, CASE 
            WHEN COMM IS NULL 
               THEN SAL
               ELSE SAL+COMM
       END as CTC 
FROM EMP;
--* all emp in dept in 10 and 20
SELECT *
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 20
--* sum of salary of all emp
SELECT SUM(SAL) AS [SUM OF SALARY]
FROM EMP
--* avg salary of all emp
SELECT AVG(SAL) AS [AVG OF SALARY]
FROM EMP
--* all emp in same dept of 'smith'
SELECT *
FROM EMP
WHERE DEPTNO IN 
			(SELECT DEPTNO
			 FROM EMP
			 WHERE ENAME = 'SMITH'
			); 
--* emp having same salary of 'blake'
SELECT *
FROM EMP
WHERE SAL IN 
			(SELECT SAL
			 FROM EMP
			 WHERE ENAME = 'BLAKE'
			); 
--* DEPT WISE NO OF EMP
SELECT DEPTNO, COUNT(*) AS NO_EMP
FROM EMP
GROUP BY DEPTNO;
--* JOB WISE NO OF EMP
SELECT JOB, COUNT(*)AS NO_EMP
FROM EMP
GROUP BY JOB;
--* DEPT WISE, JOB WISE NO OF EMP
SELECT DEPTNO, JOB, COUNT(*) AS NO_EMP
FROM EMP
GROUP BY JOB, DEPTNO;
--* DISPLAY EMP WITH THEIR DEPT NAME
SELECT ENAME, DNAME
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;
--* ALL DEPTS WITH EMP IF ANY
SELECT DNAME, ENAME
FROM DEPT D LEFT OUTER JOIN EMP E
ON E.DEPTNO = D.DEPTNO;
--* ALL DEPTS WHICH DOES NOT HAVE AN EMP
SELECT D.DEPTNO,DNAME, ENAME
FROM DEPT D 
LEFT OUTER JOIN EMP E
ON D.DEPTNO = E.DEPTNO
WHERE E.ENAME IS NULL;
--* ALL EMP NAME AND THEIR BOSS
SELECT X.ENAME, ISNULL(Y.ENAME, 'CEO') AS BOSS
FROM EMP X 
LEFT OUTER JOIN EMP Y
ON X.MGR = Y.EMPNO;
--* ALL EMP NAME, DEPT NAME AND HIS MANAGER NAME
SELECT E1.ENAME, D.DNAME, E2.ENAME
FROM EMP E1 
JOIN DEPT D 
ON E1.DEPTNO = D.DEPTNO
LEFT OUTER JOIN EMP E2
ON E1.MGR = E2.EMPNO;
--* DEPT WISE, JOB WISE, SUM OF THE SALARY OF THE EMP 
--* WHOSE SALARY GREATER THAN 2000 AND DISPLAY IN THE 
--* OREDR OF SOME OF SALARY
